name: Python Unit Tests

on:
  push:
    branches: [ develop ]
    paths:
      - '**.py'
      - 'scripts/**'
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/python_tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - 'scripts/**'
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/python_tests.yml'

jobs:
  python_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Tests
        run: |
          pytest
