name: Build Android App (Test)

on:
  push:
    branches: [ feature/manager-app ]
    paths:
      - 'app/**'

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'

      - name: Install Dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Build APK
        working-directory: ./app
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/app/outputs/flutter-apk/app-release.apk
